create table темы_дипломных_работ
(
    id            bigint generated by default as identity
        primary key,
    название_темы varchar(255),
    год           integer,
    отчество      varchar(255),
    группа        varchar(255),
    имя           varchar(255),
    фамилия       varchar(255)
);

alter table темы_дипломных_работ
    owner to postgres;

create table диапазон_стипендий
(
    id            bigint generated by default as identity
        primary key,
    нижний_порог  double precision,
    сумма         double precision,
    верхний_порог double precision
);

alter table диапазон_стипендий
    owner to postgres;

create table пользователи
(
    id           bigint generated by default as identity
        primary key,
    отчество     varchar(255),
    фото_профиля varchar(255),
    логин        varchar(255),
    имя          varchar(255),
    пароль       varchar(255),
    роль         varchar(255)
        constraint пользователи_роль_check
            check (("роль")::text = ANY
                   ((ARRAY ['ADMIN'::character varying, 'TEACHER'::character varying, 'USER'::character varying])::text[])),
    фамилия      varchar(255)
);

alter table пользователи
    owner to postgres;

create table заметки
(
    id            bigint generated by default as identity
        primary key,
    дата_создания timestamp(6) not null,
    режим_доступа varchar(255) not null
        constraint заметки_режим_доступа_check
            check (("режим_доступа")::text = ANY ((ARRAY ['ME'::character varying, 'ALL'::character varying])::text[])),
    содержание    text         not null,
    заголовок     text         not null
);

alter table заметки
    owner to postgres;

create table специальности
(
    id                     bigint generated by default as identity
        primary key,
    название_специальности varchar(255) not null
);

alter table специальности
    owner to postgres;

create table группы
(
    id               bigint generated by default as identity
        primary key,
    номер_курса      bigint       not null,
    название_группы  varchar(255) not null,
    id_специальности bigint       not null
        constraint fkc2gka6oga8o6f3bfqmcojqsou
            references специальности
);

alter table группы
    owner to postgres;

create table студенты
(
    id                     bigint generated by default as identity
        primary key,
    средний_балл           double precision not null,
    комментарий_к_студенту varchar(255)     not null,
    отчество               varchar(255)     not null,
    фото_профиля           varchar(255),
    имя                    varchar(255)     not null,
    фамилия                varchar(255)     not null,
    id_группы              bigint           not null
        constraint fkk65fvlrya4es4equ3jm2jy7fi
            references группы
);

alter table студенты
    owner to postgres;

create table взыскания
(
    id          bigint generated by default as identity
        primary key,
    описание    varchar(255) not null,
    дата_конца  timestamp(6) not null,
    дата_начала timestamp(6) not null,
    id_студента bigint       not null
        constraint fkr5dtrf7j55ue0p68tw66gqngl
            references студенты
);

alter table взыскания
    owner to postgres;

create table надбавки
(
    id               bigint generated by default as identity
        primary key,
    дата_конца       timestamp(6)     not null,
    сумма            double precision not null,
    дата_начала      timestamp(6)     not null,
    причина_надбавки varchar(255)     not null,
    id_студента      bigint           not null
        constraint fkmo8rh884ild744j0gt6fhieiy
            references студенты
);

alter table надбавки
    owner to postgres;

create table архив
(
    id             bigint generated by default as identity
        primary key,
    дата_архивации varchar(255) not null
);

alter table архив
    owner to postgres;

insert into пользователи (отчество, фото_профиля, логин, имя, пароль, роль, фамилия)
values 
('Витальевна', NULL, 'user1', 'Наталья', '$2a$10$uJy8bYS8gifZubD47njwnuZuzp19BgxTFEtgd4NbPI/TNF6tBozHW', 'ADMIN', 'Мальгина');
