const IMAGES = {
    LOGO: `${process.env.PUBLIC_URL}/img/logo.png`,
    HELLO_HAND: `${process.env.PUBLIC_URL}/img/hello.webp`,
    MAIN_IMAGE: `${process.env.PUBLIC_URL}/img/main_image.png`,
    MAIN_IMAGE_TWO: `${process.env.PUBLIC_URL}/img/main_image2.png`,
    CLAPPER: `${process.env.PUBLIC_URL}/img/topics_search.gif`,
    TABLE_SEARCH_BACKGROUND: `${process.env.PUBLIC_URL}/img/table.gif`,
    LOGIN_BACKGROUND: `${process.env.PUBLIC_URL}/img/login_background.jpg`,
    LOGIN_PICTURE: `${process.env.PUBLIC_URL}/img/login_1.png`,
    SECUIRY_IMAGE: `${process.env.PUBLIC_URL}/img/security-icon.png`,
    GIF_BACKGROUND: `${process.env.PUBLIC_URL}/img/background.gif`,
    JPG_BACKGROUND: `${process.env.PUBLIC_URL}/img/background.jpg`,
    NOT_FOUND_GIF: `${process.env.PUBLIC_URL}/img/notFound.gif`,
    STATS_1: `${process.env.PUBLIC_URL}/img/1.png`,
    STATS_2: `${process.env.PUBLIC_URL}/img/2.png`,
    STATS_3: `${process.env.PUBLIC_URL}/img/3.png`,
    STATS_4: `${process.env.PUBLIC_URL}/img/4.png`,
    STATS_5: `${process.env.PUBLIC_URL}/img/5.png`,
    STATS_6: `${process.env.PUBLIC_URL}/img/6.png`,
    STATS_7: `${process.env.PUBLIC_URL}/img/7.png`,
    DATE: `${process.env.PUBLIC_URL}/img/date.png`,
    TIME: `${process.env.PUBLIC_URL}/img/time.png`,
    TRANSITION: `${process.env.PUBLIC_URL}/img/transition.png`,
    GROUPS_GIF: `${process.env.PUBLIC_URL}/img/anim.gif`,
    ALL_STATS_1: `${process.env.PUBLIC_URL}/img/1_2.png`,
    ALL_STATS_2: `${process.env.PUBLIC_URL}/img/1_1.png`,
    STATS_EMOJI: `${process.env.PUBLIC_URL}/img/stats.jpg`,
    NOT_FOUND_PERSONAL: `${process.env.PUBLIC_URL}/img/not_found_personal.jpg`,
    ROW_INFO: `${process.env.PUBLIC_URL}/img/rowInfo.gif`
};

export default IMAGES;
